<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testTestsuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-05-16T20:11:57</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9d704d59-7fee-41e4-a471-3f73df42c2a1</testSuiteGuid>
   <testCaseLink>
      <guid>1d098d4b-aab2-42da-a371-87f1eee60dc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify all side menus  and links  are displayed correctly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11ed88d3-5d40-4c3e-9d58-74e2db81a4b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc8b3a42-de32-4e21-a185-097f32507155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43e8e3a4-3482-4769-9fc7-d0c271a0a227</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43043440-ae6f-4218-b4fd-66ad0c15d68d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d7e7d51-c2dd-4d02-a894-b1c3c063c730</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
