<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_CurrentlyActiveThrottlingRules</name>
   <tag></tag>
   <elementGuidId>60933b05-4038-47e2-933b-e84ad5aaed4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='el-tabs__nav']/div[3]</value>
   </webElementProperties>
</WebElementEntity>
