<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_TreasuryDashboard</name>
   <tag></tag>
   <elementGuidId>ea90a100-a978-46e3-b646-852bef0af055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Treasury')]/ancestor::div/following-sibling::ul//a[contains(text(),'Dashboard')]</value>
   </webElementProperties>
</WebElementEntity>
